djez_user:
    resource: "@DjezUserBundle/Resources/config/routing.yml"
    prefix:   /

djez_data_modele:
    resource: "@DjezDataModeleBundle/Resources/config/routing.yml"
    prefix:   /

djez_admin:
    resource: "@DjezAdminBundle/Resources/config/routing.yml"
    prefix:   /

djez_client:
    resource: "@DjezClientBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
