
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'ABARTH');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'AC');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'ALFA ROMEO');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'ALPINE');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'ASTON MARTIN');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'AUDI');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'AUSTIN HEALEY');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'BENTLEY');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'BMW');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'BUGATTI');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'CADILLAC');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'CATERHAM');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'CHEVROLET');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'CHRYSLER');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'CITROEN');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'DODGE');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'FERRARI');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'FIAT');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'FORD');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'HONDA');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'HUMMER');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'HYUNDAI');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'INFINITI');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'JAGUAR');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'JEEP');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'KIA');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'LAMBORGHINI');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'LANCIA');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'LAND ROVER');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'LEXUS');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'LOTUS');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'MASERATI');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'MAZDA');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'MCLAREN');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'MERCEDES');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'MG');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'MINI');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'MITSUBISHI');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'MORGAN');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'NISSAN');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'OPEL');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'PEUGEOT');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'PORSCHE');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'RENAULT');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'ROLLS-ROYCE');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'SAAB');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'SEAT');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'SUBARU');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'SUZUKI');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'TESLA');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'TOYOTA');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'TRIUMPH');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'TVR');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'VOLKSWAGEN');;
insert into Marques(dateCreation, dateModification, libelleMarque) values(CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'VOLVO');;