insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(35,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Amg Gt');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(35,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Citan');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(35,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Classe A');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(35,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Classe B');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(35,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Classe C');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(35,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Classe C Break');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(35,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Classe C Coupe');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(35,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Classe Cla');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(35,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Classe Cla Shooting Brake');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(35,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Classe Cls');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(35,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Classe Cls Shooting Brake');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(35,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Classe E');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(35,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Classe E Break');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(35,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Classe E Cabriolet');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(35,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Classe E Coupe');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(35,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Classe G');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(35,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Classe Gl');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(35,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Classe Gla');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(35,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Classe Gle Coupe');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(35,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Classe Glk');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(35,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Classe M');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(35,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Classe S');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(35,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Classe S Coupe');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(35,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Classe Sl');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(35,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Classe V');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(35,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Slk');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(35,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Viano');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(35,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Vito Tourer');;