insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(54,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Cc');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(54,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Coccinelle');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(54,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Coccinelle Cabriolet');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(54,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Cross Caddy');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(54,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'E-Golf');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(54,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'E-Up');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(54,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Eco Up');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(54,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Eos');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(54,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Golf');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(54,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Golf Cabriolet');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(54,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Golf Plus');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(54,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Golf Sportsvan');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(54,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Golf Sw');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(54,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Jetta Hybrid');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(54,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Passat');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(54,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Passat Sw');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(54,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Polo');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(54,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Scirocco');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(54,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Sharan');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(54,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Tiguan');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(54,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Touareg');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(54,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Touran');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(54,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Up!');;