insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(41,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Adam');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(41,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Adam Rocks');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(41,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Adam S');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(41,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Agila');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(41,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Ampera');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(41,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Antara');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(41,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Astra');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(41,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Astra Gtc');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(41,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Astra Sports Tourer');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(41,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Cascada');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(41,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Combo Tour');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(41,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Corsa');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(41,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Insignia');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(41,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Insignia Country Tourer');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(41,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Insignia Sports Tourer');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(41,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Insignia Sports Tourer Opc');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(41,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Karl');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(41,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Meriva');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(41,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Mokka');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(41,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Vivaro Combi');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(41,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Zafira');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(41,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Zafira Tourer');;