insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(40,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'370z Coupe 2015');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(40,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'370z Roadster');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(40,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'E-Nv200 Evalia');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(40,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'E-Nv200 Evalia Flex');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(40,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Evalia');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(40,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Gt-R');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(40,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Gt-R 2015');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(40,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Juke');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(40,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Leaf');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(40,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Leaf Flex');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(40,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Micra');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(40,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Murano');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(40,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Navara');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(40,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Note');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(40,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Nv400 Combi');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(40,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Pathfinder');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(40,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Pulsar');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(40,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Qashqai');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(40,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'X-Trail');;