insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'A1');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'A1 Sportback');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'A3');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'A3 Cabriolet');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'A3 Sportback');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'A4');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'A4 Allroad');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'A4 Avant');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'A6');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'A6 Cabriolet');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'A6 Sportback');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'A6');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'A6 Allroad Quattro');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'A6 Avant');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'A7 Sportback');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'A8');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Q3');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Q6');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Q7');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'R8');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'R8 Spyder');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Rs Q3');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Rs4 Avant');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Rs6');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Rs6 Cabriolet');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Rs6 Avant');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Rs7 Sportback');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'S1');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'S1 Sportback');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'S3');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'S3 Berline');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'S3 Cabriolet');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'S3 Sportback');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'S4');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'S4 Avant');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'S6');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'S6 Cabriolet');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'S6 Sportback');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'S6');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'S6 Avant');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'S7 Sportback');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'S8');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Sq6');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Tt Coupe');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Tt Roadster');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Tt Rs');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Tt Rs Roadster');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Tts Coupe');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Tts Roadster');;