insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(42,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'108');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(42,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'2008');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(42,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'207 Cc');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(42,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'208');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(42,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'3008');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(42,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'308');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(42,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'308 Cc');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(42,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'308 Sw');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(42,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'4008');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(42,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'5008');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(42,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'508');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(42,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'508 Hybrid4');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(42,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'508 Rxh');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(42,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'508 Sw');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(42,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Bipper Tepee');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(42,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Boxer Combi');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(42,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Ion');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(42,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Partner');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(42,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Rcz');;