insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(15,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Berlingo');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(15,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'C-Zero');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(15,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'C1');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(15,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'C1 Airscape');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(15,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'C3');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(15,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'C3 Picasso');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(15,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'C4');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(15,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'C4 Aircross');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(15,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'C4 Cactus');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(15,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'C4 Picasso');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(15,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'C5');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(15,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'C5 Crosstourer');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(15,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'C5 Tourer');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(15,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Grand C4 Picasso');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(15,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Jumper Combi');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(15,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Jumpy');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(15,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Nemo');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(15,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Ds3');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(15,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Ds3 Cabriolet');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(15,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Ds4');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(15,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Ds5');;