insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(44,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Captur');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(44,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Clio');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(44,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Clio Estate');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(44,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Espace V');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(44,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Grand Kangoo');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(44,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Grand Scenic');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(44,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Kangoo');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(44,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Koleos');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(44,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Laguna');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(44,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Laguna Coupe');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(44,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Laguna Estate');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(44,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Latitude');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(44,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Megane');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(44,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Megane Cc');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(44,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Megane Coupe');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(44,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Megane Estate');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(44,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Scenic');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(44,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Scenic Xmod');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(44,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Trafic Combi');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(44,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Twingo');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(44,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Twizy');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(44,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Zoe');;