
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'I3');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'I8');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'M3');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'M4 Cabriolet');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'M4 Coupe');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'M5');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'M6 Cabriolet');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'M6 Cabriolet F12 M Lci');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'M6 Coupe');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'M6 Coupe F13 M Lci');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'M6 Gran Coupe');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'M6 Gran Coupe F06 M Lci');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Serie 1 3 Portes');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Serie 1 3 Portes F21 Lci');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Serie 1 5 Portes');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Serie 1 5 Portes F20 Lci');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Serie 2 Active Tourer');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Serie 2 Cabriolet F23');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Serie 2 Coupe');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Serie 2 Gran Tourer F46');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Serie 3');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Serie 3 Gt');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Serie 3 Touring');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Serie 4 Cabriolet');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Serie 4 Coupe');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Serie 4 Gran Coupe');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Serie 5');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Serie 5 Gt');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Serie 5 Touring');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Serie 6');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Serie 6 Cabriolet');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Serie 6 Cabriolet F12 Lci');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Serie 6 Coupe F13 Lci');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Serie 6 Gran Coupe');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Serie 6 Gran Coupe F06 Lci');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Serie 7');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'X1');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'X3');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'X4');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'X5');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'X5 M F85');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'X6');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'X6 M F86');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Z4');;