insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(19,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'B-Max');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(19,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'C-Max');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(19,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Ecosport');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(19,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Fiesta');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(19,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Focus');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(19,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Focus Sw');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(19,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Galaxy');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(19,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Grand C-Max');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(19,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Ka');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(19,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Kuga');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(19,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Mondeo');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(19,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Mondeo Hybrid');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(19,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Mondeo Sw');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(19,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Mustang Convertible');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(19,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Mustang Fastback');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(19,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'S-Max');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(19,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Tourneo Connect');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(19,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Tourneo Courier');;
insert into Modeles(idMarque, dateCreation, dateModification, libelleModele) values(19,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Transit Kombi');;